FROM eringgaard/platformio:latest
RUN sudo apt-get update
RUN sudo apt-get install libcpprest-dev -y
RUN sudo apt install libgpgme-dev -y
RUN sudo apt-get install swig3.0 -y
RUN sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
RUN sudo apt-get install python3-tk -y